{
 "title": "kube-netc-demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_sent",
     "legendFormat": "{{source_address}}({{source_name}})➡{{destination_address}}({{destination_name}})"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_recv",
     "legendFormat": "{{source_address}}({{source_name}})➡{{destination_address}}({{destination_name}})"
    }
   ]
  },
  {
   "title": "Bytes Sent Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_sent_per_second",
     "legendFormat": "{{source_address}}({{source_name}})➡{{destination_address}}({{destination_name}})"
    }
   ]
  },
  {
   "title": "Bytes Received Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_recv_per_second",
     "legendFormat": "{{source_address}}({{source_name}})➡{{destination_address}}({{destination_name}})"
    }
   ]
  },
  {
   "title": "Number of Connections to Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_connections", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}